In [9]:
import networkx as nx
import matplotlib.pyplot as plt
import time
from networkx.algorithms.community import greedy_modularity_communities
from sklearn.cluster import SpectralClustering
from sklearn.preprocessing import StandardScaler, normalize

In [4]:
#G=nx.read_gml('/content/sample_data/dolphins.gml',label='id')
G=nx.read_gml('/content/karate.gml',label='id')
#G = nx.read_pajek('/content/sample_data/jazz.net')

In [14]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA



In [17]:
start=time.time()

W = nx.adjacency_matrix(G)
print(W.todense())

# degree matrix
D = np.diag(np.sum(np.array(W.todense()), axis=1))
print('degree matrix:')
print(D)
# laplacian matrix
L = D - W
print('laplacian matrix:')
print(L)

e, v = np.linalg.eig(L)
# eigenvalues
print('eigenvalues:')
print(e)
# eigenvectors
print('eigenvectors:')
print(v)

X = pd.DataFrame(v)

pca = PCA(n_components = 2)
X_principal = pca.fit_transform(X)
X_principal = pd.DataFrame(X_principal)
X_principal.columns = ['C1', 'C2']

spectral_model_rbf = SpectralClustering()
labels_rbf = spectral_model_rbf.fit_predict(X_principal)
end = time.time()
print(f"Total runtime of the program is {end - start}")


[[0 1 1 ... 1 0 0]
 [1 0 1 ... 0 0 0]
 [1 1 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 1 1]
 [0 0 1 ... 1 0 1]
 [0 0 0 ... 1 1 0]]
degree matrix:
[[16  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 10 ...  0  0  0]
 ...
 [ 0  0  0 ...  6  0  0]
 [ 0  0  0 ...  0 12  0]
 [ 0  0  0 ...  0  0 17]]
laplacian matrix:
[[16 -1 -1 ... -1  0  0]
 [-1  9 -1 ...  0  0  0]
 [-1 -1 10 ...  0 -1  0]
 ...
 [-1  0  0 ...  6 -1 -1]
 [ 0  0 -1 ... -1 12 -1]
 [ 0  0  0 ... -1 -1 17]]
eigenvalues:
[ 1.81366960e+01  1.70551712e+01  1.33061223e+01  1.09210675e+01
  9.77724095e+00  6.99619703e+00  6.51554463e+00  6.33159222e+00
 -3.15388410e-16  5.37859508e+00  4.68525227e-01  4.58079267e+00
  4.48000767e+00  4.27587682e+00  9.09247664e-01  1.12501072e+00
  1.25940411e+00  2.48709173e+00  2.74915718e+00  3.01396297e+00
  3.47218740e+00  3.24206748e+00  3.37615409e+00  1.59928308e+00
  1.76189862e+00  1.82605521e+00  1.95505045e+00  5.61803399e+00
  3.38196601e+00  2.00000000e+00  2.00000000e+00  2.00000000e+00
  